### PR TITLE
Search for WWDR across all keychains

### PR DESCRIPTION
**Pull request by sheepsteak**
On my MacBook Pro (Mojave 10.14.6, Xcode 10.3) the `passkit-keys` program failed to find my Apple WWDR key. I found that this is because mine is in the System keychain rather than the Login keychain 🤷‍♂️. Removing the keychain to search (`login.keychain`) found it for me.

Something else I found is that if I *did* want to search a specific keychain it wasn't enough to put `System.keychain` or `login.keychain`, it had to be the full path to it (`/Library/Keychains/System.keychain`, for example). So I'd end up with a command looking like this:

```sh
security find-certificate -p -c "Apple Worldwide Developer Relations Certification Authority" /Library/Keychains/System.keychain
```

Hopefully the change in this PR should enable it to work for a lot more people.

I'm also confused about the line in the README:

> The Apple Worldwide Developer Relations Certification Authority certificate is not needed anymore since it is already included in this package.

If this is the case can we delete this code to find the WWDR altogether?

### CODE REVIEW

**Comment by tinovyatkin** [comment]
Yes, this code may actually be deleted completely or we may keep it in case somebody would like to provide their own copy of Apple certificate for some reason...

**Comment by samj** [comment]
Took me longer than it should have to work out why this was breaking — had to double click wwdr.pem to install it first. Suggest updating instructions to be more prescriptive?

```
% ./pass-js/bin/passkit-keys <directory> 
Extracting Apple WWDR certificate into directory <directory>
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
child_process.js:632
    throw err;
    ^

Error: Command failed: security find-certificate -p -c Apple Worldwide Developer Relations Certification Authority
    at checkExecSyncError (child_process.js:611:11)
    at execFileSync (child_process.js:629:15)
    at Object.<anonymous> (/Users/samj/Development/GitHub/pass-js/bin/passkit-keys:34:13)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 44,
  signal: null,
  output: [ null, <Buffer >, null ],
  pid: 88516,
  stdout: <Buffer >,
  stderr: null
}

```

**Comment by tinovyatkin** [comment]
@samj PR is always welcome!

**Pull request merged**
