### PR TITLE
Create json schema for pass.json

### PR DESCRIPTION
**Pull request by brayovsky**
Creates a schema for a pass json file using documentation from [PassKit Package Format Reference](https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html#//apple_ref/doc/uid/TP40012026-CH2-SW6)

Solves #77

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#77: [New Feature] Create JSON schema for pass.json](https://issuehunt.io/repos/99531365/issues/77)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by tinovyatkin** [comment]
Thank you @brayovsky , great work here! It missing, however, semantic fields, as described in #75 - while they are not part of this library yet, they must be part of JSON schema as fully documented fields.
Could you add that?

Thank you!

**Comment by brayovsky** [comment]
Certainly @tinovyatkin

**Comment by tinovyatkin** [comment]
@brayovsky also Apple Wallet is very strict to have dates and color encoding in exact format, for example `"format": "date-time"` is way more allowance that actually permitted here. Could you add RegExp patterns for validation dates as W3C date (see for example https://github.com/destinationstransfers/passkit/blob/4ed067f27a2d13f528d6b4acd0beaa7b7409c39b/src/lib/w3cdate.ts#L12) and `rgb(xx, xx, xx)` strings (see https://github.com/destinationstransfers/passkit/blob/4ed067f27a2d13f528d6b4acd0beaa7b7409c39b/src/lib/pass-color.ts#L6)?

**Comment by brayovsky** [comment]
@tinovyatkin updated. I've added semantics to fields definition so they can be used in either auxiliary, primary, secondary, back or header fields depending on the scenario in play.

**Comment by tinovyatkin** [comment]
Thank you! Great job!

**Pull request merged**
